# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Ruby

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby-version: ['3.1']
    steps:
    - uses: actions/checkout@v4
    - run: sudo apt update -y
    - run: sudo apt install -y ruby-full bundler 
    - run: sudo bundle install
    - run: sudo bundle exec jekyll build
    - name: Set up SSH
      run: |
        mkdir -p ~/.ssh
        echo "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan -p 22 ${{ secrets.HOST }} >> ~/.ssh/known_hosts
    - name: Copy to server 
      run: |
        scp -r ./_site/* ${{ secrets.USER }}@${{ secrets.HOST }}:/var/www/html/